version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:3000
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/var/app/front/src:ro
